### PR TITLE
Tag form fix

### LINKED ISSUE #48: Tags in Spark Form don't wrap

### PR DESCRIPTION
**Pull request by sko3ar**
added flex wrap to tags to prevent overflow
closes #48

### CODE REVIEW

File: src/forms/SparkForm/SparkForm.js [hunk 1]
```diff
@@ -124,7 +122,7 @@ const SparkForm = ({
           </Link>
         )}
       </RadioInput>
-      <div>
+      <div className="tags">
```
Comment (aml3ed) [inline src/forms/SparkForm/SparkForm.js:125]: Classnames should be inherited from the `style` object imported in the components

**Review by aml3ed — CHANGES_REQUESTED** [review]
Just remove that class that isn't used and hardcoded

**Review by aml3ed — APPROVED** [review]
